### ISSUE TITLE
[Contoh Perusahaan] PT Xirka Silicon Technology

### ISSUE THREAD

**Issue by evadantir** [evadantir/pkl-d4a2014-jtk#1]
# PT Xirka Silicon Technology

**Profil Singkat Perusahaan:**
Perusahaan yang mengembangkan teknologi WiMax dan juga mengembangkan desain chipset perangkat elektronik.

**Alamat:** Kompleks Puri Syailendra, Jl. Lemah Neundeut Kav.30 Setrasari, 
Bandung, 40163 Indonesia

**URL:** http://xirkachipset.com/ 

**No. Telp. Perusahaan:** 
T.(+62)22-2014-189
F.(+62)22-2014-253

**Contact Person:**
Nama: Ismed Daulay
Jabatan: HRD
E-mail: ismed.daulay@xirkacipset.com
No. Telp/HP: 081320931928

Surat ditujukan  ke **HRD** via **info@xirkachipset.com**

**Comment by saifulwebid** [comment]
Informasinya bukan disimpan di sini ... Kalau informasinya sudah final, langsung ditaruh di README.md.

Bisa dieksekusi?
