### ISSUE TITLE
Goers

### ISSUE THREAD

**Issue by evadantir** [evadantir/pkl-d4a2014-jtk#10]
**Alamat:** 
GOERS SPACE
Jalan Kemang Raya No. 8A
Jakarta Selatan 12730

Goers Bandung
Jl. Dago Asri No B 23, Dago, Coblong, Kota Bandung, Jawa Barat 40135
**URL:** https://goersapp.com/careers/

**No. Telp. Perusahaan:** 

**Surat ditujukan ke:** hello@goersapp.com

**Profil Singkat Perusahaan:**
We are a daily going out app, that serves information of cool events and activities for Indonesian audiences. We also provide partners with event management platform to track and measure the success of event performance. Everything we provide are personalized to cater to both audiences and partners.

**Comment by saifulwebid** [comment]
Maksudnya ini lagi dikontak sama dua orang berarti ya?

**Comment by saifulwebid** [comment]
Just asking. Asking doesn't mean that I disagree.

**Comment by evadantir** [comment]
hehe sebetulnya udh dari sebelumnya mau unassign hilda 😅 waktu awal memang ngeassign hilda juga, karena kita berdua sama-sama minat ke perusahaan ini, tapi setelah mikir-mikir kayanya bakalan lebih efektif kalau yang nanyain satu orang aja, dan pas diiliat hilda juga udah banyak diassign ke issue yang lain
lalu...kebetulan pas km comment jadi keingetan, jadi ya sekalian aja unassign hilda, jadi unassignnya bukan karena mengasumsikan kamunya ga setuju 😀

**Comment by saifulwebid** [comment]
I see. 👍

**Comment by saifulwebid** [comment]
- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by evadantir** [comment]
Dear Eva,

Terima kasih atas emailnya.

1. Silahkan langsung mendaftarkan diri melalui form di website dan mengirim CV ke email yg tertera sesuai arahan di formulir.
2. Saat ini, kontak HR bisa langsung ke bagian customer care Goers di +628111961996 atas nama Ayu.

Terima kasih

**Comment by evadantir** [comment]
Dear Eva,

Terima kasih emailnya. Tidak ada persyaratan khusus untuk internship.

Kami melihat dari kualifikasi skill dan experience juga.

Terima kasih
