### ISSUE TITLE
RUMAHITBDG

### ISSUE THREAD

**Issue by hildanisa** [evadantir/pkl-d4a2014-jtk#11]
**Alamat:** Bandung Barat, Sariwangi, Parongpong

**URL:** http://rumahitbdg.com/

**No. Telp. Perusahaan:** +62 81322 042234

**Profil Singkat Perusahaan:**

Jasa Pembuatan Web site, Aplikasi Perkantoran dan IT Konsultan

**Comment by rubiyantoprmn** [comment]
Sedang menunggu jawaban dari Perusahaan terkait

**Comment by rubiyantoprmn** [comment]
<info@rumahitbdg.com>
selamat pagi,

silahkan kan ajukan surat keterangan pengantar dari dan disertakan cv dari masing2 mahasiswa yg akan KKP.

ditujukan ke m.taufic, project manajer, 081322042234, m.taufic@rumahitbdg.com

nuhun.

**Comment by saifulwebid** [comment]
- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by saifulwebid** [comment]
Close issue-nya bukan lewat commit, ya? Manual?

**Comment by evadantir** [comment]
cara close lewat commitnya gimana? 😦

**Comment by saifulwebid** [comment]
Private message.
