### ISSUE TITLE
Belant Persada

### ISSUE THREAD

**Issue by rubiyantoprmn** [evadantir/pkl-d4a2014-jtk#13]
**Alamat:** Ruko The Suite Apartment, Jl. Soekarno Hatta Blok D No.689, Jatisari, Buahbatu, Kota Bandung, Jawa Barat 40612

**URL:** http://belant.net/

**No. Telp. Perusahaan:** Phone: 022-87793105/ Fax: 022-87793106

**Profil Singkat Perusahaan:**

Belant Persada adalah perusahaan IT Consultant yang didirikan pada tahun 2001. Dengan professional-professional muda yang menyukai tantangan, Belant mengembangkan bisnis dan solusi melalui 4 divisi Software Development, ERP, Datacenter & Infrastrucutre, serta Managed Services.

**Comment by rubiyantoprmn** [comment]
<arya.adhi@belant.net>
Dear rubiyanto,

Untuk internship bisa menghubungi saya:

Arya Adhi
Corporate Services Director
085861110900
arya.adhi@belant.net

Regards,
Arya Adhi

Belum ada balasan mengenai peserta KP/PKL yang diterima apa saja

**Comment by saifulwebid** [comment]
- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by saifulwebid** [comment]
Close issue-nya bukan lewat commit, ya? Manual?
