### ISSUE TITLE
PT Rekadia Solusi Teknologi

### ISSUE THREAD

**Issue by berpergian** [evadantir/pkl-d4a2014-jtk#16]
**Alamat:** 

- Jakarta : Grand Slipi Tower Lt.42 (Jl.Letjend S Parman 22-24)
- Bandung : Jl. Pasir Salam Selatan I no. 16A

**URL:** http://rekadia.co.id/

**No. Telp. Perusahaan:** (+62)21 30490220

**Profil Singkat Perusahaan:**

Dengan moto 'A Helpful Company', kami percaya bahwa kami dapat menjadi partner dalam mengembangkan perusahaan Anda.

**Comment by saifulwebid** [comment]
- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by berpergian** [comment]
Bisa kontak ke saya saja

Yosef Sukianto
Manager HRD
08112030095
