### ISSUE TITLE
Mitrais

### ISSUE THREAD

**Issue by saifulwebid** [evadantir/pkl-d4a2014-jtk#19]
**Alamat:**

- Bali: Jl. Bypass Ngurah Rai, gg. Mina Utama No. 1, ​Suwung 80223, Bali​
- Bandung: Jl. Prof. Surya Sumantri No. 8-D Bandung 40164
- Yogyakarta: Jl. Sidobali No. 2 Muja Muju, Umbulharjo, Yogyakarta, 55165

**URL:** https://www.mitrais.com/id

**No. Telp. Perusahaan:** 0807 1222 222

**Profil Singkat Perusahaan:**

Mitrais adalah perusahaan teknologi terkemuka di Indonesia, Australia, Singapore, and Vietnam.

Kami memberikan layanan software development yang terbaik di Indonesia dengan pusat pengembangan di Jakarta, Bandung, Yogyakarta and Bali.

Mitrais juga menjual dan mendukung sistem-sistem untuk rumah sakit dan pertambangan. Dengan lebih dari 400 staf Mitrais mampu memenuhi kebutuhan berbagai perusahaan dengan layanan personal.

Didirikan sejak tahun 1991, Mitrais telah mengembangkan software atau menginstal sistem untuk 500 klien.

---

Selanjutnya, hal-hal yang perlu ditanyakan ke perusahaan ini adalah:

- [ ] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [ ] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [ ] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [ ] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by saifulwebid** [comment]
@evadantir kenapa di-close?

**Comment by evadantir** [comment]
20:21 M. Husain Fadhlullah @Eva Danti Rahmanita Soal Mitrais cuma bisa menerima 2.5 bulan, kata Maul
