### ISSUE TITLE
41 Studio

### ISSUE THREAD

**Issue by wordstary** [evadantir/pkl-d4a2014-jtk#20]
Alamat :
5th Building Setra Mas Residence 
Cimahi 40525 
West Java - Indonesia

URL : http://www.41studio.com/

No. Telp. Perusahaan:
+62 22 8600 1718
+62 22 2066 0058
+62 819 3207 8901

Profil Singkat Perusahaan :

We specialize in Ruby on Rails, iOS and Android development.

For over 10 years in Ruby on Rails Development by creating websites such as ERPs, CRMs, E-commerce, Social Networks etc and also Mobile Applications. We handle variety of clients which spread all over the world. Client's satisfaction is one of our achievements, build applications according to the needs and desires of the client is our target. We develop creative and innovative ideas from the clients, making it is not only becomes a big idea, but into something that can be enjoyed by users.

We make a good working environment and become the beacon of IT solutions. Through our excellent and extraordinary team, communicative and fun. We are ready to help you to make all your ideas become reality.

Selanjutnya, hal-hal yang perlu ditanyakan ke perusahaan ini adalah:

- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by evadantir** [comment]
Hi Mutiara !

sure i can answer all your question.
1. yes, we are opened for your major ( D3 / D4 Teknik Informatika )
2. you can do it, for maximal 4,5 month.
3. you can contact to me for further information, fyi your refference latter should adressed to Mr Hendra Nicholas as our CEO.
