### ISSUE TITLE
Kazee

### ISSUE THREAD

**Issue by berpergian** [evadantir/pkl-d4a2014-jtk#21]
**Alamat:** _Belum ditemukan_

**URL:** https://www.kazee.id/

**No. Telp. Perusahaan:** _Belum ditemukan_

**Profil Singkat Perusahaan:**

Kazee merupakan platform yang dikembangkan dengan tujuan untuk melakukan analisis berbagai media seperti media sosial, forum, media berita dan lainnya

---

Selanjutnya, hal-hal yang perlu ditanyakan ke perusahaan ini adalah:

- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by berpergian** [comment]
Dari kuliah umum Big Data Analytics waktu itu, kuota ada sekitar 6 orang lagi
email dikirimkan ke ariya@kazee.id (kalau salah email koreksi)

**Comment by evadantir** [comment]
Boleh untuk alamat bisa dikirimkan ke sini. Kontak via email saja tidak masalah.

LPIK ITB | LEMBAGA PENGEMBANGAN INOVASI DAN KEWIRAUSAHAAN.

Jl. Ganesa No. 15
Bandung-Jawa Barat, BDO
Indonesia 40132
TEL: +62 22 2501006
FAX: +62 22 2534163

KONTAK SANI : +62 878-2459-2825
