### ISSUE TITLE
UrbanIndo

### ISSUE THREAD

**Issue by Ashyels** [evadantir/pkl-d4a2014-jtk#8]
Alamat: Jl. Karang Tinggal 14, Bandung - West Java, Indonesia 40162, Kota Bandung

URL: https://www.urbanindo.com

No. Telp. Perusahaan +6222 2035 028 / +6222 4268 663

Profil Singkat Perusahaan:

Perusahaan ini adalah perusahaan teknologi yang bergerak di bidang properti (jual-beli properti).

**Comment by Ashyels** [comment]
Ini bisa tolong ditambahin label "telah-dikontak" atau "mendapat-kontak-hrd"?

**Comment by saifulwebid** [comment]
Kalau sudah dikontak, mulai buat commit untuk menutup issue. @nikosibarani
bisa bantu?

**Comment by nikosibarani** [comment]
ready @saifulwebid ..

**Comment by saifulwebid** [comment]
- [x] _Contact person_ perusahaan, meliputi: nama CP, jabatan, alamat e-mail, dan nomor telepon/handphone pribadi;
- [x] Ke departemen/divisi mana surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: HRD, atau lainnya -- tanyakan pada perusahaan!)
- [x] Melalui media apa surat dari jurusan mengenai permohonan KP/PKL harus ditujukan? (misal: lewat pos? kalau lewat pos, ke alamat mana? lewat e-mail? kalau lewat e-mail, ke alamat mana?)
- [x] Apakah perusahaan menerima D3 saja, D4 saja, atau keduanya?

**Comment by Ashyels** [comment]
1. CP: 0812 2440 5627 (a.n. Mirsa, Divisi HR, email hr@urbanindo.com)
2. Permohonan KP/PKL bisa dikirimkan ke divisi HR UrbanIndo
3. bisa lewat email ataupun surat (email: hr@urbanindo.com)
4. Perusahaan menerima D3 dan D4
